<h1>Capstone Project - The Battle of the Neighborhoods (Week 1)</h1>

<h3>Applied Data Science Capstone by IBM/Coursera</h3>

<h2>Introduction: Business Problem</h2>

In this project we will try to get the most common venue categories in each district, and then use this feature to group the district into clusters. This report will be targeted to stakeholders interested in opening a venue in Ubud, Bali, Indonesia.

<h2>Data</h2>

Ubud has a total of 8 districts. In order to segment the district and explore them, we will essentially need a dataset that contains the districts and find the latitude and longitude using geopy library.

In [6]:
import pandas as pd

column_names = ['District', 'Latitude', 'Longitude']
ubud_region=pd.DataFrame(columns=column_names)
ubud_region

Empty DataFrame
Columns: [District, Latitude, Longitude]
Index: []

In [7]:
from geopy.geocoders import Nominatim
district = ['Kedewatan, Ubud', 'Petulu, Ubud', 'Lodtunduh, Ubud', 'Mas, Ubud', 'Peliatan, Ubud', 'Sayan, Ubud', 'Singakerta, Ubud', 'Ubud']
latitudes = []
longitudes = []

geolocator = Nominatim(user_agent="ubud_explorer")
for vil in village:
  location = geolocator.geocode(vil)
  latitude = location.latitude
  longitude = location.longitude
  latitudes.append(latitude)
  longitudes.append(longitude)

for n in range(0,8):
  ubud_region = ubud_region.append({'District':district[n],
                                  'Latitude': latitudes[n],
                                  'Longitude':longitudes[n]}, ignore_index=True)
ubud_region

           District  Latitude   Longitude
0   Kedewatan, Ubud -8.484786  115.245827
1      Petulu, Ubud -8.477163  115.276407
2   Lodtunduh, Ubud -8.552164  115.260830
3         Mas, Ubud -8.545034  115.273189
4    Peliatan, Ubud -8.518865  115.269199
5       Sayan, Ubud -8.512834  115.240697
6  Singakerta, Ubud -8.526700  115.244694
7              Ubud -8.506898  115.262293

<h2>Foursquare</h2>

to get the location, name and category of venue within 1 kilometers from the Ubud's districts center, we use Foursquare API.

<h2> Methodology </h2>

In this project We will limit our analysis to area ~1km around each district center.

In first step we will collect the required data: location and category of every venue within 1km from the Ubud's districts center.

Second step in our analysis will be exploration of 10 top venues in each district. This exploration can be a reference for stakeholders who interested to open a venue in Ubud.

In third step and final step we group the district into cluster.